In [1]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\Admin\Desktop\project_new\project.xlsx",
    sheet_name="Loan_Default"
)

In [4]:
df.shape

(148670, 42)

In [5]:
df = df.iloc[:, :34]

In [6]:
df.shape

(148670, 34)

In [7]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [8]:
df["loan_limit"] = df["loan_limit"].fillna("cf")
df["approv_in_adv"] = df["approv_in_adv"].fillna("nopre")
df["loan_purpose"] = df["loan_purpose"].fillna("p3")
df["term"] = df["term"].fillna(360)
df["Neg_ammortization"] = df["Neg_ammortization"].fillna("not_neg")
df["income"] = df["income"].fillna(5760)
df["age"] = df["age"].fillna("45-54")
df["submission_of_application"] = df["submission_of_application"].fillna("to_inst")

In [9]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                       0
Gender                           0
approv_in_adv                    0
loan_type                        0
loan_purpose                     0
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                             0
Neg_ammortization                0
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                           0
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                              0
submission_of_application        0
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [10]:
df.groupby("Status")[[
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "LTV",
    "dtir1"
]].apply(lambda x: x.isnull().sum())

,rate_of_interest,Interest_rate_spread,Upfront_charges,property_value,LTV,dtir1
Status,,,,,,
0,0,0,3156,2,2,7811
1,36439,36639,36486,15096,15096,16310

In [11]:
df["Status"].value_counts()

Status
0    112031
1     36639
Name: count, dtype: int64

In [12]:
df[["Status", "loan_amount", "Credit_Score"]].groupby("Status").agg({
    "loan_amount": ["count", "mean"],
    "Credit_Score": ["count", "mean"]
})

       loan_amount                Credit_Score
             count           mean        count        mean
Status
0           112031  334990.774875       112031  699.523793
1            36639  319275.184912        36639  700.600344

In [32]:
import os

os.listdir(r"C:\Users\Admin\Desktop\project_new\Loan_Default")

['Loan_Default.csv']

In [33]:
import pandas as pd

df_csv = pd.read_csv(
    r"C:\Users\Admin\Desktop\project_new\Loan_Default\Loan_Default.csv"
)

df_csv[["Status"]].value_counts()

Status
0         112031
1          36639
Name: count, dtype: int64

In [34]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 145326 non-null  object
 3   Gender                     148670 non-null  object
 4   approv_in_adv              147762 non-null  object
 5   loan_type                  148670 non-null  object
 6   loan_purpose               148536 non-null  object
 7   Credit_Worthiness          148670 non-null  object
 8   open_credit                148670 non-null  object
 9   business_or_commercial     148670 non-null  object
 10  loan_amount                148670 non-null  int64
 11  rate_of_interest           112231 non-null  float64
 12  Interest_rate_spread       112031 non-null  float64
 13  Upfront_charges            109028 non-null  float64
 14  term                       148629 non-null  float64
 15  Neg_ammortization          148549 non-null  object
 16  interest_only              148670 non-null  object
 17  lump_sum_payment           148670 non-null  object
 18  property_value             133572 non-null  float64
 19  construction_type          148670 non-null  object
 20  occupancy_type             148670 non-null  object
 21  Secured_by                 148670 non-null  object
 22  total_units                148670 non-null  object
 23  income                     139520 non-null  float64
 24  credit_type                148670 non-null  object
 25  Credit_Score               148670 non-null  int64
 26  co-applicant_credit_type   148670 non-null  object
 27  age                        148470 non-null  object
 28  submission_of_application  148470 non-null  object
 29  LTV                        133572 non-null  float64
 30  Region                     148670 non-null  object
 31  Security_Type              148670 non-null  object
 32  Status                     148670 non-null  int64
 33  dtir1                      124549 non-null  float64
dtypes: float64(8), int64(5), object(21)
memory usage: 38.6+ MB

In [35]:
df_csv.duplicated().sum()

np.int64(0)

In [36]:
df_csv["ID"].duplicated().sum()

np.int64(0)

In [37]:
df = df_csv.copy()

In [38]:
df.shape

(148670, 34)

In [39]:
df = df_csv.copy()
df.shape

(148670, 34)

In [40]:
df["loan_limit"] = df["loan_limit"].fillna("cf")
df["approv_in_adv"] = df["approv_in_adv"].fillna("nopre")
df["loan_purpose"] = df["loan_purpose"].fillna("p3")
df["term"] = df["term"].fillna(360)
df["Neg_ammortization"] = df["Neg_ammortization"].fillna("not_neg")
df["income"] = df["income"].fillna(5760)
df["age"] = df["age"].fillna("45-54")
df["submission_of_application"] = df["submission_of_application"].fillna("to_inst")

In [41]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                       0
Gender                           0
approv_in_adv                    0
loan_type                        0
loan_purpose                     0
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                             0
Neg_ammortization                0
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                           0
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                              0
submission_of_application        0
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [42]:
df[[
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "LTV",
    "dtir1"
]].isnull().mean() * 100

rate_of_interest        24.509989
Interest_rate_spread    24.644515
Upfront_charges         26.664425
property_value          10.155378
LTV                     10.155378
dtir1                   16.224524
dtype: float64

In [43]:
df.groupby("Status")[[
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "LTV",
    "dtir1"
]].apply(lambda x: x.isnull().sum())

,rate_of_interest,Interest_rate_spread,Upfront_charges,property_value,LTV,dtir1
Status,,,,,,
0,0,0,3156,2,2,7811
1,36439,36639,36486,15096,15096,16310

In [44]:
df.groupby("Status")[[
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "LTV",
    "dtir1"
]].apply(lambda x: x.isnull().mean() * 100)

,rate_of_interest,Interest_rate_spread,Upfront_charges,property_value,LTV,dtir1
Status,,,,,,
0,0.000000,0.0,2.817077,0.001785,0.001785,6.972177
1,99.454134,100.0,99.582412,41.201998,41.201998,44.515407

In [45]:
df.groupby("Status")[["loan_limit", "loan_type", "loan_purpose", "Gender"]].agg(
    lambda x: x.value_counts().to_dict()
)

,loan_limit,loan_type,loan_purpose,Gender
Status,,,,
0,"{'cf': 105367, 'ncf': 6664}","{'type1': 87398, 'type2': 13590, 'type3': 11043}","{'p4': 42209, 'p3': 42037, 'p1': 25594, 'p2': ...","{'Joint': 33466, 'Male': 31255, 'Sex Not Avail..."
1,"{'cf': 33325, 'ncf': 3314}","{'type1': 25775, 'type2': 7172, 'type3': 3692}","{'p3': 14031, 'p4': 12590, 'p1': 8935, 'p2': 1...","{'Male': 11091, 'Sex Not Available': 10767, 'J..."

In [46]:
id="7k31p"
df[[
    "loan_amount",
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "term",
    "property_value",
    "income",
    "Credit_Score",
    "LTV",
    "dtir1"
]].describe()

,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,property_value,income,Credit_Score,LTV,dtir1
count,1.486700e+05,112231.000000,112031.000000,109028.000000,148670.000000,1.335720e+05,148670.000000,148670.000000,133572.000000,124549.000000
mean,3.311177e+05,4.045476,0.441656,3224.996127,335.143438,4.978935e+05,6883.647811,699.789103,72.746457,37.732932
std,1.839093e+05,0.561391,0.513043,3251.121510,58.402488,3.599353e+05,6300.067060,115.875857,39.967603,10.545435
min,1.650000e+04,0.000000,-3.638000,0.000000,96.000000,8.000000e+03,0.000000,500.000000,0.967478,5.000000
25%,1.965000e+05,3.625000,0.076000,581.490000,360.000000,2.680000e+05,3840.000000,599.000000,60.474860,31.000000
50%,2.965000e+05,3.990000,0.390400,2596.450000,360.000000,4.180000e+05,5760.000000,699.000000,75.135870,39.000000
75%,4.365000e+05,4.375000,0.775400,4812.500000,360.000000,6.280000e+05,8280.000000,800.000000,86.184211,45.000000
max,3.576500e+06,8.000000,3.357000,60000.000000,360.000000,1.650800e+07,578580.000000,900.000000,7831.250000,61.000000

In [47]:
df[df["LTV"] > 100]["LTV"].describe()

count    1799.000000
mean      124.975078
std       301.244725
min       100.760286
25%       102.759740
50%       104.425837
75%       109.445339
max      7831.250000
Name: LTV, dtype: float64

In [48]:
(df["LTV"] > 100).sum()

np.int64(1799)

In [49]:
df[df["LTV"] > 500][[
    "ID",
    "loan_amount",
    "property_value",
    "LTV",
    "Status"
]].sort_values("LTV", ascending=False)

            ID  loan_amount  property_value      LTV  Status
16951    41841       626500          8000.0  7831.25       0
55286    80176       536500          8000.0  6706.25       0
47807    72697       416500          8000.0  5206.25       0
65238    90128       376500          8000.0  4706.25       0
46287    71177       236500          8000.0  2956.25       1
123343  148233       186500          8000.0  2331.25       0

In [50]:
(df["property_value"] == 8000).sum()

np.int64(6)

In [51]:
df[df["property_value"] == 8000][[
    "loan_amount",
    "property_value",
    "LTV",
    "Status"
]].describe()

         loan_amount  property_value          LTV    Status
count       6.000000             6.0     6.000000  6.000000
mean   396500.000000          8000.0  4956.250000  0.166667
std    169115.345253             0.0  2113.941816  0.408248
min    186500.000000          8000.0  2331.250000  0.000000
25%    271500.000000          8000.0  3393.750000  0.000000
50%    396500.000000          8000.0  4956.250000  0.000000
75%    506500.000000          8000.0  6331.250000  0.000000
max    626500.000000          8000.0  7831.250000  1.000000

In [52]:
print("Zero income:", (df["income"] == 0).sum())
print("Zero interest rate:", (df["rate_of_interest"] == 0).sum())
print("Zero upfront charges:", (df["Upfront_charges"] == 0).sum())

Zero income: 1260
Zero interest rate: 1
Zero upfront charges: 20770

In [53]:
df[df["rate_of_interest"] == 0][[
    "ID",
    "loan_amount",
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "income",
    "LTV",
    "Status"
]]

,ID,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,property_value,income,LTV,Status
36272,61162,406500,0.0,-3.638,NaN,638000.0,0.0,63.714734,0

In [54]:
df[df["income"] == 0][[
    "ID",
    "loan_amount",
    "income",
    "property_value",
    "LTV",
    "Status"
]].head(10)

        ID  loan_amount  income  property_value        LTV  Status
42   24932       466500     0.0             NaN        NaN       1
143  25033       686500     0.0             NaN        NaN       1
208  25098       366500     0.0        858000.0  42.715618       1
301  25191       636500     0.0             NaN        NaN       1
409  25299       516500     0.0             NaN        NaN       1
463  25353       356500     0.0             NaN        NaN       1
586  25476       216500     0.0             NaN        NaN       1
589  25479       456500     0.0             NaN        NaN       1
593  25483       136500     0.0        138000.0  98.913043       1
743  25633       316500     0.0             NaN        NaN       1

In [55]:
df.loc[df["rate_of_interest"] == 0, "rate_of_interest"] = pd.NA

In [56]:
df.groupby("Status")["income"].apply(lambda x: (x == 0).sum())

Status
0       8
1    1252
Name: income, dtype: int64

In [57]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                       0
Gender                           0
approv_in_adv                    0
loan_type                        0
loan_purpose                     0
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36440
Interest_rate_spread         36639
Upfront_charges              39642
term                             0
Neg_ammortization                0
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                           0
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                              0
submission_of_application        0
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [58]:
id_cols = [
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "LTV",
    "dtir1"
]

df[id_cols].isnull().sum(axis=1).value_counts().sort_index()

0    101430
1     10232
2       520
3     20378
4      1014
6     15096
Name: count, dtype: int64

In [59]:
df["missing_count"] = df[id_cols].isnull().sum(axis=1)

pd.crosstab(
    df["missing_count"],
    df["Status"]
)

Status              0      1
missing_count
0              101430      0
1               10232      0
2                 367    153
3                   2  20376
4                   0   1014
6                   0  15096

In [60]:
df["interest_rate_missing"] = df["rate_of_interest"].isnull().astype(int)

In [61]:
df["interest_rate_missing"].value_counts()

interest_rate_missing
0    112230
1     36440
Name: count, dtype: int64

In [62]:
df["spread_missing"] = df["Interest_rate_spread"].isnull().astype(int)
df["upfront_charges_missing"] = df["Upfront_charges"].isnull().astype(int)
df["property_value_missing"] = df["property_value"].isnull().astype(int)
df["ltv_missing"] = df["LTV"].isnull().astype(int)
df["dtir1_missing"] = df["dtir1"].isnull().astype(int)

In [63]:
df[[
    "interest_rate_missing",
    "spread_missing",
    "upfront_charges_missing",
    "property_value_missing",
    "ltv_missing",
    "dtir1_missing"
]].sum()

interest_rate_missing      36440
spread_missing             36639
upfront_charges_missing    39642
property_value_missing     15098
ltv_missing                15098
dtir1_missing              24121
dtype: int64

In [64]:
numeric_cols = [
    "loan_amount",
    "rate_of_interest",
    "Interest_rate_spread",
    "Upfront_charges",
    "property_value",
    "income",
    "Credit_Score",
    "LTV",
    "dtir1"
]

df[numeric_cols].describe()

,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,property_value,income,Credit_Score,LTV,dtir1
count,1.486700e+05,112230.000000,112031.000000,109028.000000,1.335720e+05,148670.000000,148670.000000,133572.000000,124549.000000
mean,3.311177e+05,4.045512,0.441656,3224.996127,4.978935e+05,6883.647811,699.789103,72.746457,37.732932
std,1.839093e+05,0.561264,0.513043,3251.121510,3.599353e+05,6300.067060,115.875857,39.967603,10.545435
min,1.650000e+04,2.125000,-3.638000,0.000000,8.000000e+03,0.000000,500.000000,0.967478,5.000000
25%,1.965000e+05,3.625000,0.076000,581.490000,2.680000e+05,3840.000000,599.000000,60.474860,31.000000
50%,2.965000e+05,3.990000,0.390400,2596.450000,4.180000e+05,5760.000000,699.000000,75.135870,39.000000
75%,4.365000e+05,4.375000,0.775400,4812.500000,6.280000e+05,8280.000000,800.000000,86.184211,45.000000
max,3.576500e+06,8.000000,3.357000,60000.000000,1.650800e+07,578580.000000,900.000000,7831.250000,61.000000

In [65]:
Q1 = df["LTV"].quantile(0.25)
Q3 = df["LTV"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

print("Outliers:", ((df["LTV"] < lower) | (df["LTV"] > upper)).sum())

Q1: 60.47486034
Q3: 86.18421053
IQR: 25.709350190000002
Lower bound: 21.910835055
Upper bound: 124.748235815
Outliers: 1882

In [66]:
ltv_outliers = df[
    (df["LTV"] < lower) | (df["LTV"] > upper)
]

pd.crosstab(
    ltv_outliers["Status"],
    columns="count"
)

col_0   count
Status
0        1481
1         401

In [67]:
ltv_outliers.groupby("Status")["LTV"].agg(
    ["count", "min", "median", "max"]
)

        count       min     median      max
Status
0        1481  2.072943  16.838431  7831.25
1         401  0.967478  18.814168  2956.25

In [68]:
df[df["LTV"] > 500][
    ["ID", "loan_amount", "property_value", "LTV", "Status"]
].sort_values("LTV", ascending=False)

            ID  loan_amount  property_value      LTV  Status
16951    41841       626500          8000.0  7831.25       0
55286    80176       536500          8000.0  6706.25       0
47807    72697       416500          8000.0  5206.25       0
65238    90128       376500          8000.0  4706.25       0
46287    71177       236500          8000.0  2956.25       1
123343  148233       186500          8000.0  2331.25       0

In [69]:
Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower_income = Q1 - 1.5 * IQR
upper_income = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_income)
print("Upper bound:", upper_income)
print("Outliers:", ((df["income"] < lower_income) | (df["income"] > upper_income)).sum())

Q1: 3840.0
Q3: 8280.0
IQR: 4440.0
Lower bound: -2820.0
Upper bound: 14940.0
Outliers: 7636

In [70]:
df[df["income"] > 14940][
    ["ID", "income", "loan_amount", "Credit_Score", "Status"]
].sort_values("income", ascending=False).head(20)

            ID    income  loan_amount  Credit_Score  Status
62237    87127  578580.0      1086500           585       1
33621    58511  377220.0       476500           883       0
65351    90241  374400.0       656500           633       0
46142    71032  335880.0       726500           644       0
60996    85886  335880.0       726500           877       0
8892     33782  329460.0       766500           582       0
114559  139449  322860.0       446500           772       1
117307  142197  312000.0       556500           660       0
117248  142138  240000.0       406500           673       0
31674    56564  235980.0       436500           788       0
141741  166631  198060.0       576500           549       1
1055     25945  189360.0       476500           702       0
144910  169800  186480.0       256500           680       1
22369    47259  177720.0       106500           531       1
31537    56427  171420.0       626500           695       0
72598    97488  157980.0      1386500           796       1
106871  131761  157320.0       726500           541       0
51734    76624  154440.0      1366500           867       0
2403     27293  149820.0       996500           860       0
111585  136475  148860.0       996500           805       0

In [71]:
Q1 = df["loan_amount"].quantile(0.25)
Q3 = df["loan_amount"].quantile(0.75)

IQR = Q3 - Q1

lower_loan = Q1 - 1.5 * IQR
upper_loan = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_loan)
print("Upper bound:", upper_loan)
print("Outliers:", ((df["loan_amount"] < lower_loan) | (df["loan_amount"] > upper_loan)).sum())

Q1: 196500.0
Q3: 436500.0
IQR: 240000.0
Lower bound: -163500.0
Upper bound: 796500.0
Outliers: 1895

In [72]:
df[df["loan_amount"] > upper_loan][
    ["ID", "loan_amount", "property_value", "income", "Credit_Score", "Status"]
].sort_values("loan_amount", ascending=False).head(20)

            ID  loan_amount  property_value    income  Credit_Score  Status
4321     29211      3576500       5208000.0  119340.0           751       1
98146   123036      3346500             NaN   33840.0           538       1
121640  146530      3006500             NaN  114000.0           774       1
54519    79409      3006500       5758000.0   66000.0           798       0
86408   111298      3006500       3508000.0   43320.0           511       1
3762     28652      3006500       5258000.0   50580.0           620       0
114333  139223      2986500       5508000.0   61500.0           791       0
42200    67090      2926500       4878000.0   64020.0           663       1
68421    93311      2706500       4508000.0   10800.0           767       1
128145  153035      2626500             NaN   32940.0           764       1
36524    61414      2606500       4608000.0   23820.0           526       1
115252  140142      2596500             NaN   13080.0           803       1
33282    58172      2506500       3858000.0   88440.0           713       0
75192   100082      2506500       4218000.0   34800.0           680       0
17114    42004      2476500      16508000.0   84000.0           809       1
84667   109557      2406500       3008000.0   27840.0           710       1
66160    91050      2406500             NaN   34260.0           586       1
14605    39495      2396500       2298000.0   54780.0           869       1
135391  160281      2276500       3508000.0   33540.0           726       1
145085  169975      2276500       3508000.0   27960.0           885       1

In [73]:
Q1 = df["Upfront_charges"].quantile(0.25)
Q3 = df["Upfront_charges"].quantile(0.75)

IQR = Q3 - Q1

lower_upfront = Q1 - 1.5 * IQR
upper_upfront = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_upfront)
print("Upper bound:", upper_upfront)
print("Outliers:", ((df["Upfront_charges"] < lower_upfront) | 
                    (df["Upfront_charges"] > upper_upfront)).sum())

Q1: 581.49
Q3: 4812.5
IQR: 4231.01
Lower bound: -5765.025000000001
Upper bound: 11159.015
Outliers: 2880

In [74]:
df[df["Upfront_charges"] > upper_upfront][
    ["ID", "Upfront_charges", "loan_amount", "property_value", "income", "Status"]
].sort_values("Upfront_charges", ascending=False).head(20)

            ID  Upfront_charges  loan_amount  property_value   income  Status
3762     28652         60000.00      3006500       5258000.0  50580.0       0
27166    52056         53485.78      1306500       1708000.0  36000.0       0
30636    55526         38437.50      1756500       2508000.0  28980.0       0
113641  138531         38375.00      1356500       1858000.0  37560.0       0
55892    80782         37604.38      1716500       2398000.0  16320.0       0
146563  171453         35192.50      1276500       1728000.0  16440.0       0
116695  141585         33268.00       856500       1128000.0  23040.0       0
136008  160898         32850.00      1096500       1328000.0   7500.0       0
125142  150032         32825.25       746500       1298000.0   9480.0       0
140825  165715         32647.00       886500       1128000.0  15180.0       0
112169  137059         32120.37      1396500       2008000.0  64680.0       0
80277   105167         32000.00       916500       1308000.0  11940.0       0
31363    56253         31180.79      1026500       1278000.0  14700.0       0
53337    78227         30500.00       936500       1048000.0  32460.0       0
94357   119247         30493.50      1066500       1438000.0  20400.0       0
78216   103106         29775.00       816500       1078000.0   7440.0       0
47794    72684         29725.00       826500       1188000.0  14760.0       0
144917  169807         29015.49       676500        908000.0   9480.0       0
132607  157497         28833.00       796500        998000.0  13980.0       0
108963  133853         28696.73       856500       1288000.0  12000.0       0

In [75]:
Q1 = df["property_value"].quantile(0.25)
Q3 = df["property_value"].quantile(0.75)

IQR = Q3 - Q1

lower_property = Q1 - 1.5 * IQR
upper_property = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_property)
print("Upper bound:", upper_property)
print("Outliers:", ((df["property_value"] < lower_property) |
                    (df["property_value"] > upper_property)).sum())

Q1: 268000.0
Q3: 628000.0
IQR: 360000.0
Lower bound: -272000.0
Upper bound: 1168000.0
Outliers: 5266

In [76]:
df[df["property_value"] > upper_property][
    ["ID", "property_value", "loan_amount", "income", "Credit_Score", "Status"]
].sort_values("property_value", ascending=False).head(20)

            ID  property_value  loan_amount    income  Credit_Score  Status
17114    42004      16508000.0      2476500   84000.0           809       1
99460   124350      12008000.0      1006500   19380.0           616       1
42558    67448      11008000.0       106500   67020.0           751       1
100371  125261      10008000.0      2106500   41760.0           862       1
124997  149887       9268000.0       256500   33360.0           788       0
94285   119175       8508000.0      1006500   66720.0           898       0
118331  143221       7608000.0      2146500  127920.0           612       1
43173    68063       6908000.0       426500   26100.0           570       0
6575     31465       6508000.0       576500    8820.0           669       0
4448     29338       6408000.0       336500   10440.0           686       0
115649  140539       6208000.0       486500   70860.0           660       0
94047   118937       6108000.0       386500   17700.0           683       0
68626    93516       6058000.0       366500   22800.0           700       0
1704     26594       5808000.0       676500   13320.0           807       0
54519    79409       5758000.0      3006500   66000.0           798       0
51139    76029       5508000.0       956500   19200.0           871       1
114333  139223       5508000.0      2986500   61500.0           791       0
53319    78209       5508000.0       706500   13920.0           573       0
23588    48478       5308000.0       276500   15540.0           718       0
3762     28652       5258000.0      3006500   50580.0           620       0

In [77]:
Q1 = df["Credit_Score"].quantile(0.25)
Q3 = df["Credit_Score"].quantile(0.75)

IQR = Q3 - Q1

lower_credit = Q1 - 1.5 * IQR
upper_credit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_credit)
print("Upper bound:", upper_credit)

print("Outliers:", ((df["Credit_Score"] < lower_credit) |
                    (df["Credit_Score"] > upper_credit)).sum())

Q1: 599.0
Q3: 800.0
IQR: 201.0
Lower bound: 297.5
Upper bound: 1101.5
Outliers: 0

In [78]:
Q1 = df["dtir1"].quantile(0.25)
Q3 = df["dtir1"].quantile(0.75)

IQR = Q3 - Q1

lower_dtir = Q1 - 1.5 * IQR
upper_dtir = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_dtir)
print("Upper bound:", upper_dtir)

print("Outliers:", ((df["dtir1"] < lower_dtir) |
                    (df["dtir1"] > upper_dtir)).sum())

Q1: 31.0
Q3: 45.0
IQR: 14.0
Lower bound: 10.0
Upper bound: 66.0
Outliers: 2013

In [79]:
df[(df["dtir1"] < lower_dtir) | (df["dtir1"] > upper_dtir)][
    ["ID", "dtir1", "income", "loan_amount", "Credit_Score", "Status"]
].sort_values("dtir1").head(20)

            ID  dtir1   income  loan_amount  Credit_Score  Status
114647  139537    5.0   5160.0       466500           687       0
105313  130203    5.0   1320.0       246500           812       1
71020    95910    5.0   4320.0        66500           693       0
43450    68340    5.0  14700.0       356500           673       0
105933  130823    5.0   6120.0       136500           723       0
106090  130980    5.0  19380.0       616500           533       0
43577    68467    5.0  15600.0       266500           743       0
43806    68696    5.0  10200.0       326500           559       0
70688    95578    5.0   9960.0       286500           630       0
70173    95063    5.0  13620.0       296500           731       1
24940    49830    5.0   9180.0       256500           613       0
71261    96151    5.0   5760.0       196500           675       0
106996  131886    5.0   7500.0       256500           835       0
24866    49756    5.0   8460.0       156500           754       0
44065    68955    5.0   5940.0       176500           677       1
69892    94782    5.0  10260.0       296500           763       0
107736  132626    5.0   5820.0        66500           857       0
108478  133368    5.0  16680.0       426500           877       0
108497  133387    5.0  12780.0       316500           859       0
108973  133863    5.0   6660.0       226500           873       0

In [80]:
df[df["dtir1"] > upper_dtir][
    ["ID", "dtir1", "income", "loan_amount", "Credit_Score", "Status"]
].sort_values("dtir1", ascending=False).head(20)

Empty DataFrame
Columns: [ID, dtir1, income, loan_amount, Credit_Score, Status]
Index: []

In [81]:
df[df["dtir1"] > upper_dtir][
    ["ID", "dtir1", "income", "loan_amount", "Credit_Score", "Status"]
].sort_values("dtir1", ascending=False).head(20)

Empty DataFrame
Columns: [ID, dtir1, income, loan_amount, Credit_Score, Status]
Index: []

In [82]:
Q1 = df["rate_of_interest"].quantile(0.25)
Q3 = df["rate_of_interest"].quantile(0.75)

IQR = Q3 - Q1

lower_rate = Q1 - 1.5 * IQR
upper_rate = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_rate)
print("Upper bound:", upper_rate)

print("Outliers:", ((df["rate_of_interest"] < lower_rate) |
                    (df["rate_of_interest"] > upper_rate)).sum())

Q1: 3.625
Q3: 4.375
IQR: 0.75
Lower bound: 2.5
Upper bound: 5.5
Outliers: 855

In [83]:
df[(df["rate_of_interest"] < lower_rate) |
   (df["rate_of_interest"] > upper_rate)][
    ["ID", "rate_of_interest", "loan_amount", "income", "Credit_Score", "Status"]
].sort_values("rate_of_interest").head(20)

            ID  rate_of_interest  loan_amount    income  Credit_Score  Status
33732    58622             2.125       476500   19140.0           551       0
29960    54850             2.250       226500   24120.0           619       0
142543  167433             2.250       556500   11040.0           610       0
64039    88929             2.250       476500  131940.0           741       0
42742    67632             2.250       266500   12600.0           542       0
6869     31759             2.375       496500   19620.0           635       0
132945  157835             2.375       566500   11460.0           898       0
140968  165858             2.475       486500    9660.0           826       0
70452    95342             2.475       716500   11040.0           756       0
114198  139088             5.625       426500   14340.0           787       0
83447   108337             5.625       346500    7140.0           621       0
52960    77850             5.625       336500   12960.0           564       0
83513   108403             5.625       276500    5700.0           888       0
30554    55444             5.625       116500    5280.0           675       0
91845   116735             5.625       386500    6660.0           846       0
113594  138484             5.625       126500    6600.0           658       0
113403  138293             5.625       906500   51180.0           531       0
112970  137860             5.625       296500    5700.0           780       0
30954    55844             5.625       246500    3480.0           791       0
59885    84775             5.625       106500    5640.0           587       0

In [84]:
df[df["rate_of_interest"] > upper_rate][
    ["ID", "rate_of_interest", "loan_amount", "income", "Credit_Score", "Status"]
].sort_values("rate_of_interest", ascending=False).head(20)

            ID  rate_of_interest  loan_amount   income  Credit_Score  Status
9429     34319             8.000       106500   3360.0           886       0
28731    53621             7.750       306500   9360.0           889       0
95531   120421             7.500       326500  15180.0           817       0
79073   103963             7.500       176500   8460.0           578       0
40906    65796             7.375       166500  10440.0           608       0
122882  147772             7.125       106500   7260.0           819       0
20614    45504             7.000       466500  10260.0           525       0
102085  126975             6.875       126500   7500.0           566       0
100917  125807             6.750       126500  11580.0           569       0
13177    38067             6.750       176500  21600.0           844       0
72596    97486             6.750       176500   6300.0           875       0
65383    90273             6.750       106500   3960.0           696       0
14366    39256             6.750       156500   6900.0           799       0
99473   124363             6.500       106500   3300.0           648       0
57602    82492             6.500       116500   5640.0           598       0
78727   103617             6.500       106500   3960.0           609       0
56519    81409             6.375       996500  16080.0           900       0
69611    94501             6.250       206500   9720.0           869       0
26591    51481             6.240       106500   6480.0           695       0
57242    82132             6.240       256500   9600.0           805       0

In [85]:
Q1 = df["Interest_rate_spread"].quantile(0.25)
Q3 = df["Interest_rate_spread"].quantile(0.75)

IQR = Q3 - Q1

lower_spread = Q1 - 1.5 * IQR
upper_spread = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_spread)
print("Upper bound:", upper_spread)

print("Outliers:", ((df["Interest_rate_spread"] < lower_spread) |
                    (df["Interest_rate_spread"] > upper_spread)).sum())

Q1: 0.076
Q3: 0.7754
IQR: 0.6994
Lower bound: -0.9731000000000002
Upper bound: 1.8245
Outliers: 445

In [86]:
df[(df["Interest_rate_spread"] < lower_spread) |
   (df["Interest_rate_spread"] > upper_spread)][
    ["ID", "Interest_rate_spread", "rate_of_interest",
     "loan_amount", "Credit_Score", "Status"]
].sort_values("Interest_rate_spread").head(20)

,ID,Interest_rate_spread,rate_of_interest,loan_amount,Credit_Score,Status
36272,61162,-3.6380,NaN,406500,567,0
84715,109605,-1.0841,2.75,416500,822,0
72290,97180,-1.0470,3.25,676500,509,0
135614,160504,-1.0462,2.75,236500,796,0
83036,107926,-1.0390,2.75,396500,894,0
96722,121612,-1.0380,2.75,356500,818,0
12941,37831,-1.0379,2.75,326500,676,0
50080,74970,-1.0343,2.75,226500,683,0
131612,156502,-1.0294,2.75,546500,822,0
93538,118428,-1.0288,2.75,416500,787,0
24971,49861,-1.0230,2.75,336500,841,0
13174,38064,-1.0176,2.75,206500,522,0
34614,59504,-1.0173,2.75,326500,812,0
105932,130822,-1.0139,2.75,726500,734,0
28542,53432,-1.0132,2.75,856500,536,0
78093,102983,-1.0089,2.75,216500,623,0
11949,36839,-1.0086,2.75,536500,879,0
86398,111288,-1.0039,2.75,326500,655,0
72155,97045,-1.0037,2.75,216500,728,0
35479,60369,-1.0014,2.75,336500,534,0

In [87]:
df[df["Interest_rate_spread"] > upper_spread][
    ["ID", "Interest_rate_spread", "rate_of_interest",
     "loan_amount", "Credit_Score", "Status"]
].sort_values("Interest_rate_spread", ascending=False).head(20)

,ID,Interest_rate_spread,rate_of_interest,loan_amount,Credit_Score,Status
9429,34319,3.3570,8.000,106500,886,0
40906,65796,2.8854,7.375,166500,608,0
102085,126975,2.7227,6.875,126500,566,0
65383,90273,2.6368,6.750,106500,696,0
79073,103963,2.5932,7.500,176500,578,0
28731,53621,2.5851,7.750,306500,889,0
1665,26555,2.5370,3.625,276500,605,0
95531,120421,2.5144,7.500,326500,817,0
99473,124363,2.4093,6.500,106500,648,0
13177,38067,2.1820,6.750,176500,844,0
20614,45504,2.1478,7.000,466500,525,0
42707,67597,2.1282,5.125,46500,875,0
122882,147772,2.0758,7.125,106500,819,0
16869,41759,2.0677,5.750,106500,659,0
57602,82492,2.0404,6.500,116500,598,0
146519,171409,2.0022,4.500,326500,507,0
104271,129161,2.0016,4.625,86500,838,0
40842,65732,1.9993,4.750,86500,632,0
29883,54773,1.9975,4.500,216500,638,0
99653,124543,1.9964,4.625,196500,811,0

In [88]:
df["term"].value_counts().sort_index()

term
96.0        194
108.0        33
120.0       510
132.0        93
144.0       263
156.0       174
165.0         1
168.0        82
180.0     12981
192.0        17
204.0        59
216.0       115
228.0        74
240.0      5859
252.0         8
264.0        43
276.0       100
280.0         1
288.0        90
300.0      2822
312.0       185
322.0         1
324.0      2766
336.0       213
348.0       260
360.0    121726
Name: count, dtype: int64

In [89]:
df["term"] = df["term"].astype(int)

In [90]:
df["term"].dtype

dtype('int64')

In [91]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 loan_limit
loan_limit
cf     138692
ncf      9978
Name: count, dtype: int64

 Gender
Gender
Male                 42346
Joint                41399
Sex Not Available    37659
Female               27266
Name: count, dtype: int64

 approv_in_adv
approv_in_adv
nopre    125529
pre       23141
Name: count, dtype: int64

 loan_type
loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

 loan_purpose
loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

 Credit_Worthiness
Credit_Worthiness
l1    142344
l2      6326
Name: count, dtype: int64

 open_credit
open_credit
nopc    148114
opc        556
Name: count, dtype: int64

 business_or_commercial
business_or_commercial
nob/c    127908
b/c       20762
Name: count, dtype: int64

 Neg_ammortization
Neg_ammortization
not_neg    133541
neg_amm     15129
Name: count, dtype: int64

 interest_only
interest_only
not_int     141560
int_only      7110
Name: count, dtype: int64

 lump_sum_payment
lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

 construction_type
construction_type
sb    148637
mh        33
Name: count, dtype: int64

 occupancy_type
occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

 Secured_by
Secured_by
home    148637
land        33
Name: count, dtype: int64

 total_units
total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

 credit_type
credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

 co-applicant_credit_type
co-applicant_credit_type
CIB    74392
EXP    74278
Name: count, dtype: int64

 age
age
45-54    34920
35-44    32818
55-64    32534
65-74    20744
25-34    19142
>74       7175
<25       1337
Name: count, dtype: int64

 submission_of_application
submission_of_application
to_inst     96014
not_inst    52656
Name: count, dtype: int64

 Region
Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

 Security_Type
Security_Type
direct      148637
Indriect        33
Name: count, dtype: int64

In [92]:
df["approv_in_adv"].value_counts(dropna=False)

approv_in_adv
nopre    125529
pre       23141
Name: count, dtype: int64

In [93]:
df["loan_type"].value_counts(dropna=False)

loan_type
type1    113173
type2     20762
type3     14735
Name: count, dtype: int64

In [94]:
df["loan_purpose"].value_counts(dropna=False)

loan_purpose
p3    56068
p4    54799
p1    34529
p2     3274
Name: count, dtype: int64

In [95]:
df["Credit_Worthiness"].value_counts(dropna=False)

Credit_Worthiness
l1    142344
l2      6326
Name: count, dtype: int64

In [96]:
df["open_credit"].value_counts(dropna=False)

open_credit
nopc    148114
opc        556
Name: count, dtype: int64

In [97]:
df["business_or_commercial"].value_counts(dropna=False)

business_or_commercial
nob/c    127908
b/c       20762
Name: count, dtype: int64

In [98]:
df["Neg_ammortization"].value_counts(dropna=False)

Neg_ammortization
not_neg    133541
neg_amm     15129
Name: count, dtype: int64

In [99]:
df["interest_only"].value_counts(dropna=False)

interest_only
not_int     141560
int_only      7110
Name: count, dtype: int64

In [100]:
df["lump_sum_payment"].value_counts(dropna=False)

lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

In [101]:
df["construction_type"].value_counts(dropna=False)

construction_type
sb    148637
mh        33
Name: count, dtype: int64

In [102]:
df["occupancy_type"].value_counts(dropna=False)

occupancy_type
pr    138201
ir      7340
sr      3129
Name: count, dtype: int64

In [103]:
df["Secured_by"].value_counts(dropna=False)

Secured_by
home    148637
land        33
Name: count, dtype: int64

In [104]:
df["total_units"].value_counts(dropna=False)

total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

In [105]:
df["credit_type"].value_counts(dropna=False)

credit_type
CIB     48152
CRIF    43901
EXP     41319
EQUI    15298
Name: count, dtype: int64

In [106]:
df["co-applicant_credit_type"].value_counts(dropna=False)

co-applicant_credit_type
CIB    74392
EXP    74278
Name: count, dtype: int64

In [107]:
df["age"].value_counts(dropna=False)

age
45-54    34920
35-44    32818
55-64    32534
65-74    20744
25-34    19142
>74       7175
<25       1337
Name: count, dtype: int64

In [108]:
df["submission_of_application"].value_counts(dropna=False)

submission_of_application
to_inst     96014
not_inst    52656
Name: count, dtype: int64

In [109]:
df["Region"].value_counts(dropna=False)

Region
North         74722
south         64016
central        8697
North-East     1235
Name: count, dtype: int64

In [110]:
df["Security_Type"].value_counts(dropna=False)

Security_Type
direct      148637
Indriect        33
Name: count, dtype: int64

In [111]:
df["Security_Type"] = df["Security_Type"].replace({
    "Indriect": "Indirect"
})

In [112]:
df["Security_Type"].value_counts(dropna=False)

Security_Type
direct      148637
Indirect        33
Name: count, dtype: int64

In [113]:
df.groupby("Status")["rate_of_interest"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count      mean  median    min  max
Status
0       112030  4.044967  3.9900  2.125  8.0
1          200  4.350500  4.3125  3.125  5.5

In [114]:
df.groupby("Status")["Interest_rate_spread"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count      mean  median    min    max
Status
0       112031  0.441656  0.3904 -3.638  3.357
1            0       NaN     NaN    NaN    NaN

In [115]:
df.groupby("Status")["Upfront_charges"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count         mean   median  min      max
Status
0       108875  3227.328554  2600.00  0.0  60000.0
1          153  1565.237974   687.85  0.0  15584.0

In [116]:
df.groupby("Status")["property_value"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count           mean    median     min         max
Status
0       112029  505606.066286  428000.0  8000.0   9268000.0
1        21543  457786.009377  348000.0  8000.0  16508000.0

In [117]:
df.groupby("Status")["LTV"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count       mean     median       min      max
Status
0       112029  72.064757  74.504405  2.072943  7831.25
1        21543  76.291468  79.362416  0.967478  2956.25

In [118]:
df.groupby("Status")["dtir1"].agg(
    ["count", "mean", "median", "min", "max"]
)

         count       mean  median  min   max
Status
0       104220  37.369267    38.0  5.0  61.0
1        20329  39.597324    42.0  5.0  61.0

In [119]:
df["dtir1"]

0         45.0
1          NaN
2         46.0
3         42.0
4         39.0
          ...
148665    48.0
148666    15.0
148667    49.0
148668    29.0
148669    44.0
Name: dtir1, Length: 148670, dtype: float64

In [120]:
df["dtir1_missing"]

0         0
1         1
2         0
3         0
4         0
         ..
148665    0
148666    0
148667    0
148668    0
148669    0
Name: dtir1_missing, Length: 148670, dtype: int64

In [121]:
df["dtir1_missing"].value_counts()

dtir1_missing
0    124549
1     24121
Name: count, dtype: int64

In [122]:
df.isnull().sum().sort_values(ascending=False)

Upfront_charges              39642
Interest_rate_spread         36639
rate_of_interest             36440
dtir1                        24121
property_value               15098
LTV                          15098
Credit_Score                     0
co-applicant_credit_type         0
age                              0
submission_of_application        0
Region                           0
ID                               0
income                           0
Security_Type                    0
Status                           0
missing_count                    0
interest_rate_missing            0
spread_missing                   0
upfront_charges_missing          0
property_value_missing           0
ltv_missing                      0
credit_type                      0
occupancy_type                   0
total_units                      0
Secured_by                       0
loan_limit                       0
Gender                           0
approv_in_adv                    0
loan_type                        0
loan_purpose                     0
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
term                             0
Neg_ammortization                0
interest_only                    0
lump_sum_payment                 0
construction_type                0
year                             0
dtir1_missing                    0
dtype: int64

In [123]:
df.drop(columns=["missing_count"], inplace=True)

In [124]:
df.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'Status', 'dtir1', 'interest_rate_missing', 'spread_missing',
       'upfront_charges_missing', 'property_value_missing', 'ltv_missing',
       'dtir1_missing'],
      dtype='object')

In [125]:
df.dtypes

ID                             int64
year                           int64
loan_limit                    object
Gender                        object
approv_in_adv                 object
loan_type                     object
loan_purpose                  object
Credit_Worthiness             object
open_credit                   object
business_or_commercial        object
loan_amount                    int64
rate_of_interest             float64
Interest_rate_spread         float64
Upfront_charges              float64
term                           int64
Neg_ammortization             object
interest_only                 object
lump_sum_payment              object
property_value               float64
construction_type             object
occupancy_type                object
Secured_by                    object
total_units                   object
income                       float64
credit_type                   object
Credit_Score                   int64
co-applicant_credit_type      object
age                           object
submission_of_application     object
LTV                          float64
Region                        object
Security_Type                 object
Status                         int64
dtir1                        float64
interest_rate_missing          int64
spread_missing                 int64
upfront_charges_missing        int64
property_value_missing         int64
ltv_missing                    int64
dtir1_missing                  int64
dtype: object

In [126]:
df.dtypes.head()

ID                int64
year              int64
loan_limit       object
Gender           object
approv_in_adv    object
dtype: object

In [2]:
df["Status"].value_counts()

Status
0    112031
1     36639
Name: count, dtype: int64

In [3]:
df["Status"].value_counts(normalize=True) * 100

Status
0    75.355485
1    24.644515
Name: proportion, dtype: float64

In [4]:
pd.crosstab(
    df["Gender"],
    df["Status"],
    normalize="index"
) * 100

Status                     0          1
Gender
Female             74.884472  25.115528
Joint              80.837701  19.162299
Male               73.808624  26.191376
Sex Not Available  71.409225  28.590775

In [5]:
pd.crosstab(
    pd.cut(
        df["Credit_Score"],
        bins=[499, 599, 699, 799, 900],
        labels=["500-599", "600-699", "700-799", "800-900"]
    ),
    df["Status"],
    normalize="index"
) * 100

Status                0          1
Credit_Score
500-599       75.369723  24.630277
600-699       75.516129  24.483871
700-799       75.713781  24.286219
800-900       74.829859  25.170141

In [6]:
pd.crosstab(
    df["loan_type"],
    df["Status"],
    normalize="index"
) * 100

Status             0          1
loan_type
type1      77.225133  22.774867
type2      65.456122  34.543878
type3      74.944011  25.055989

In [7]:
pd.crosstab(
    df["loan_purpose"],
    df["Status"],
    normalize="index"
) * 100

Status                0          1
loan_purpose
p1            74.123201  25.876799
p2            66.921197  33.078803
p3            74.977652  25.022348
p4            77.025128  22.974872

In [8]:
pd.crosstab(
    df["loan_limit"],
    df["Status"],
    normalize="index"
) * 100

Status              0          1
loan_limit
cf          76.029199  23.970801
ncf         66.786931  33.213069

In [9]:
pd.crosstab(
    df["approv_in_adv"],
    df["Status"],
    normalize="index"
) * 100

Status                 0          1
approv_in_adv
nopre          74.672808  25.327192
pre            79.106348  20.893652

In [10]:
pd.crosstab(
    df["Credit_Worthiness"],
    df["Status"],
    normalize="index"
) * 100

Status                     0          1
Credit_Worthiness
l1                 75.672315  24.327685
l2                 68.226367  31.773633

In [11]:
pd.crosstab(
    df["open_credit"],
    df["Status"],
    normalize="index"
) * 100

Status               0          1
open_credit
nopc         75.329138  24.670862
opc          82.374101  17.625899

In [12]:
pd.crosstab(
    df["business_or_commercial"],
    df["Status"],
    normalize="index"
) * 100

Status                          0          1
business_or_commercial
b/c                     65.456122  34.543878
nob/c                   76.962348  23.037652

In [13]:
pd.crosstab(
    df["interest_only"],
    df["Status"],
    normalize="index"
) * 100

Status                 0          1
interest_only
int_only       72.686357  27.313643
not_int        75.489545  24.510455

In [14]:
pd.crosstab(
    df["Neg_ammortization"],
    df["Status"],
    normalize="index"
) * 100

Status                     0          1
Neg_ammortization
neg_amm            55.403530  44.596470
not_neg            77.619547  22.380453

In [15]:
pd.crosstab(
    df["lump_sum_payment"],
    df["Status"],
    normalize="index"
) * 100

Status                    0          1
lump_sum_payment
lpsm              22.340426  77.659574
not_lpsm          76.590312  23.409688

In [16]:
df["lump_sum_payment"].value_counts()

lump_sum_payment
not_lpsm    145286
lpsm          3384
Name: count, dtype: int64

In [17]:
pd.crosstab(
    df["construction_type"],
    df["Status"],
    normalize="index"
) * 100

Status                     0           1
construction_type
mh                  0.000000  100.000000
sb                 75.372216   24.627784

In [18]:
pd.crosstab(
    df["occupancy_type"],
    df["Status"],
    normalize="index"
) * 100

Status                  0          1
occupancy_type
ir              70.013624  29.986376
pr              75.695545  24.304455
sr              72.866731  27.133269

In [19]:
pd.crosstab(
    df["Secured_by"],
    df["Status"],
    normalize="index"
) * 100

Status              0           1
Secured_by
home        75.372216   24.627784
land         0.000000  100.000000

In [20]:
pd.crosstab(
    df["total_units"],
    df["Status"],
    normalize="index"
) * 100

Status               0          1
total_units
1U           75.503140  24.496860
2U           65.470548  34.529452
3U           61.577608  38.422392
4U           70.312500  29.687500

In [21]:
df["total_units"].value_counts()

total_units
1U    146480
2U      1477
3U       393
4U       320
Name: count, dtype: int64

In [22]:
pd.crosstab(
    df["total_units"],
    df["Status"],
    normalize="index"
) * 100

Status               0          1
total_units
1U           75.503140  24.496860
2U           65.470548  34.529452
3U           61.577608  38.422392
4U           70.312500  29.687500

In [23]:
df.groupby("total_units")["Status"].agg(
    ["count", "mean"]
)

              count      mean
total_units
1U           146480  0.244969
2U             1477  0.345295
3U              393  0.384224
4U              320  0.296875

In [24]:
pd.crosstab(
    df["credit_type"],
    df["Status"],
    normalize="index"
) * 100

Status               0          1
credit_type
CIB          84.195880  15.804120
CRIF         83.765746  16.234254
EQUI          0.006537  99.993463
EXP          84.014618  15.985382

In [25]:
pd.crosstab(
    df["credit_type"],
    df["Status"]
)

Status           0      1
credit_type
CIB          40542   7610
CRIF         36774   7127
EQUI             1  15297
EXP          34714   6605

In [26]:
pd.crosstab(
    df["co-applicant_credit_type"],
    df["Status"],
    normalize="index"
) * 100

Status                            0          1
co-applicant_credit_type
CIB                       81.566566  18.433434
EXP                       69.134872  30.865128

In [27]:

pd.crosstab(
    df["age"],
    df["Status"],
    normalize="index"
) * 100

Status          0          1
age
25-34   77.807962  22.192038
35-44   77.728685  22.271315
45-54   75.953341  24.046659
55-64   74.113235  25.886765
65-74   73.144042  26.855958
<25     71.054600  28.945400
>74     69.993031  30.006969

In [28]:
pd.crosstab(
    df["submission_of_application"],
    df["Status"],
    normalize="index"
) * 100

Status                             0          1
submission_of_application
not_inst                   82.478730  17.521270
to_inst                    71.598096  28.401904

In [29]:
pd.crosstab(
    df["Region"],
    df["Status"],
    normalize="index"
) * 100

Status              0          1
Region
North       77.488558  22.511442
North-East  69.554656  30.445344
central     72.461768  27.538232
south       73.370720  26.629280

In [30]:
pd.crosstab(
    df["Security_Type"],
    df["Status"],
    normalize="index"
) * 100

Status                 0           1
Security_Type
Indriect        0.000000  100.000000
direct         75.372216   24.627784

In [31]:
df["Security_Type"] = df["Security_Type"].replace(
    "Indriect",
    "Indirect"
)

In [32]:
df["Security_Type"].value_counts()

Security_Type
direct      148637
Indirect        33
Name: count, dtype: int64

In [33]:
pd.crosstab(
    pd.qcut(df["loan_amount"], q=5),
    df["Status"],
    normalize="index"
) * 100

Status                         0          1
loan_amount
(16499.999, 176500.0]  69.495614  30.504386
(176500.0, 256500.0]   74.914744  25.085256
(256500.0, 346500.0]   76.772770  23.227230
(346500.0, 476500.0]   78.635064  21.364936
(476500.0, 3576500.0]  77.508613  22.491387

In [34]:
pd.crosstab(
    pd.qcut(df["income"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                      0          1
income
(-0.001, 3360.0]    62.750278  37.249722
(3360.0, 4920.0]    73.768898  26.231102
(4920.0, 6660.0]    77.638614  22.361386
(6660.0, 9360.0]    79.725479  20.274521
(9360.0, 578580.0]  79.707476  20.292524

In [35]:
pd.crosstab(
    pd.qcut(df["LTV"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                     0          1
LTV
(0.966, 57.682]    85.546218  14.453782
(57.682, 70.448]   87.704303  12.295697
(70.448, 79.337]   86.562804  13.437196
(79.337, 89.295]   82.107549  17.892451
(89.295, 7831.25]  77.439641  22.560359

In [36]:
pd.crosstab(
    pd.qcut(df["property_value"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                          0          1
property_value
(7999.999, 248000.0]    76.366082  23.633918
(248000.0, 358000.0]    82.738827  17.261173
(358000.0, 488000.0]    85.942075  14.057925
(488000.0, 678000.0]    87.967633  12.032367
(678000.0, 16508000.0]  86.923395  13.076605

In [37]:
pd.crosstab(
    pd.qcut(df["dtir1"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                 0          1
dtir1
(4.999, 30.0]  84.397569  15.602431
(30.0, 37.0]   88.040197  11.959803
(37.0, 42.0]   86.853430  13.146570
(42.0, 46.0]   85.374233  14.625767
(46.0, 61.0]   73.291977  26.708023

In [38]:
pd.crosstab(
    pd.qcut(df["rate_of_interest"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                    0         1
rate_of_interest
(-0.001, 3.625]   99.980292  0.019708
(3.625, 3.875]    99.762497  0.237503
(3.875, 4.125]    99.850556  0.149444
(4.125, 4.5]      99.736341  0.263659
(4.5, 8.0]        99.693340  0.306660

In [39]:
df["Status"].value_counts()

Status
0    112031
1     36639
Name: count, dtype: int64

In [40]:
pd.crosstab(df["Status"], columns="count")

col_0    count
Status
0       112031
1        36639

In [43]:
pd.crosstab(
    pd.qcut(df["rate_of_interest"], q=5, duplicates="drop"),
    df["Status"],
    normalize="index"
) * 100

Status                    0         1
rate_of_interest
(-0.001, 3.625]   99.980292  0.019708
(3.625, 3.875]    99.762497  0.237503
(3.875, 4.125]    99.850556  0.149444
(4.125, 4.5]      99.736341  0.263659
(4.5, 8.0]        99.693340  0.306660

In [45]:
df.columns.tolist()

['ID',
 'year',
 'loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'loan_amount',
 'rate_of_interest',
 'Interest_rate_spread',
 'Upfront_charges',
 'term',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'property_value',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'income',
 'credit_type',
 'Credit_Score',
 'co-applicant_credit_type',
 'age',
 'submission_of_application',
 'LTV',
 'Region',
 'Security_Type',
 'Status',
 'dtir1',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41']

In [46]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")]

In [47]:
df.shape

(148670, 34)

In [49]:
df = df.copy()

df["interest_rate_missing"] = df["rate_of_interest"].isna().astype(int)

In [50]:
df["interest_rate_missing"].value_counts()

interest_rate_missing
0    112231
1     36439
Name: count, dtype: int64

In [51]:
pd.crosstab(
    df["interest_rate_missing"],
    df["Status"],
    normalize="index"
) * 100

Status                         0           1
interest_rate_missing
0                      99.821796    0.178204
1                       0.000000  100.000000

In [52]:

pd.crosstab(
    df["interest_rate_missing"],
    df["Status"]
)

Status                      0      1
interest_rate_missing
0                      112031    200
1                           0  36439

In [54]:
df["spread_missing"] = df["Interest_rate_spread"].isna().astype(int)

In [55]:
df["spread_missing"].value_counts()

spread_missing
0    112031
1     36639
Name: count, dtype: int64

In [56]:
pd.crosstab(
    df["spread_missing"],
    df["Status"],
    normalize="index"
) * 100

Status              0      1
spread_missing
0               100.0    0.0
1                 0.0  100.0

In [57]:
pd.crosstab(
    df["spread_missing"],
    df["Status"]
)

Status               0      1
spread_missing
0               112031      0
1                    0  36639

In [58]:
df["upfront_charges_missing"] = df["Upfront_charges"].isna().astype(int)

In [59]:
pd.crosstab(
    df["upfront_charges_missing"],
    df["Status"],
    normalize="index"
) * 100

Status                           0          1
upfront_charges_missing
0                        99.859669   0.140331
1                         7.961253  92.038747

In [60]:
pd.crosstab(
    df["upfront_charges_missing"],
    df["Status"]
)

Status                        0      1
upfront_charges_missing
0                        108875    153
1                          3156  36486

In [61]:
df["property_value_missing"] = df["property_value"].isna().astype(int)

In [62]:
pd.crosstab(
    df["property_value_missing"],
    df["Status"],
    normalize="index"
) * 100

Status                          0          1
property_value_missing
0                       83.871620  16.128380
1                        0.013247  99.986753

In [63]:
pd.crosstab(
    df["property_value_missing"],
    df["Status"]
)

Status                       0      1
property_value_missing
0                       112029  21543
1                            2  15096

In [64]:
df["ltv_missing"] = df["LTV"].isna().astype(int)

In [65]:
pd.crosstab(
    df["ltv_missing"],
    df["Status"],
    normalize="index"
) * 100

Status               0          1
ltv_missing
0            83.871620  16.128380
1             0.013247  99.986753

In [66]:
pd.crosstab(
    df["ltv_missing"],
    df["Status"]
)

Status            0      1
ltv_missing
0            112029  21543
1                 2  15096

In [67]:
pd.crosstab(
    df["property_value_missing"],
    df["ltv_missing"]
)

ltv_missing                  0      1
property_value_missing
0                       133572      0
1                            0  15098

In [68]:
df = df.drop(columns=["ltv_missing"])

In [69]:
"ltv_missing" in df.columns

False

In [71]:
df["dtir1_missing"] = df["dtir1"].isna().astype(int)

In [72]:
df["dtir1_missing"].value_counts()

dtir1_missing
0    124549
1     24121
Name: count, dtype: int64

In [73]:
pd.crosstab(
    df["dtir1_missing"],
    df["Status"],
    margins=True
)

Status              0      1     All
dtir1_missing
0              104220  20329  124549
1                7811  16310   24121
All            112031  36639  148670

In [74]:
df["dtir1_missing"] = df["dtir1"].isna().astype(int)

In [75]:
missing_cols = [
    "interest_rate_missing",
    "spread_missing",
    "upfront_charges_missing",
    "property_value_missing",
    "dtir1_missing"
]

In [76]:
df[missing_cols].value_counts().sort_values(ascending=False)

interest_rate_missing  spread_missing  upfront_charges_missing  property_value_missing  dtir1_missing
0                      0               0                        0                       0                101430
1                      1               1                        0                       0                 20329
                                                                1                       1                 15096
0                      0               0                        0                       1                  7445
                                       1                        0                       0                  2788
1                      1               1                        0                       1                  1014
0                      0               1                        0                       1                   366
                       1               0                        0                       1                   153
                                       1                        0                       1                    47
                       0               1                        1                       0                     2
Name: count, dtype: int64

In [77]:
df = df.drop(columns=["spread_missing"])

In [78]:
"spread_missing" in df.columns

False

In [79]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
interest_rate_missing            0
upfront_charges_missing          0
property_value_missing           0
dtir1_missing                    0
dtype: int64

In [80]:
df.columns.tolist()

['ID',
 'year',
 'loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'loan_amount',
 'rate_of_interest',
 'Interest_rate_spread',
 'Upfront_charges',
 'term',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'property_value',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'income',
 'credit_type',
 'Credit_Score',
 'co-applicant_credit_type',
 'age',
 'submission_of_application',
 'LTV',
 'Region',
 'Security_Type',
 'Status',
 'dtir1',
 'interest_rate_missing',
 'upfront_charges_missing',
 'property_value_missing',
 'dtir1_missing']

In [81]:
pd.crosstab(
    df["income"].isna(),
    df["Status"],
    margins=True
)

Status       0      1     All
income
False   104120  35400  139520
True      7911   1239    9150
All     112031  36639  148670

In [82]:
df["income"].median()

5760.0

In [83]:
df["income"] = df["income"].fillna(df["income"].median())

In [84]:
df["income"].isna().sum()

np.int64(0)

In [85]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                           0
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
interest_rate_missing            0
upfront_charges_missing          0
property_value_missing           0
dtir1_missing                    0
dtype: int64

In [86]:
df[[
    "loan_limit",
    "approv_in_adv",
    "loan_purpose",
    "term",
    "Neg_ammortization",
    "age",
    "submission_of_application"
]].isnull().sum()

loan_limit                   3344
approv_in_adv                 908
loan_purpose                  134
term                           41
Neg_ammortization             121
age                           200
submission_of_application     200
dtype: int64

In [87]:
df["loan_limit"] = df["loan_limit"].fillna("cf")

df["approv_in_adv"] = df["approv_in_adv"].fillna("nopre")

df["loan_purpose"] = df["loan_purpose"].fillna("p3")

df["term"] = df["term"].fillna(360)

df["Neg_ammortization"] = df["Neg_ammortization"].fillna("not_neg")

df["age"] = df["age"].fillna("45-54")

df["submission_of_application"] = df["submission_of_application"].fillna("to_inst")

In [88]:
df[[
    "loan_limit",
    "approv_in_adv",
    "loan_purpose",
    "term",
    "Neg_ammortization",
    "age",
    "submission_of_application"
]].isnull().sum()

loan_limit                   0
approv_in_adv                0
loan_purpose                 0
term                         0
Neg_ammortization            0
age                          0
submission_of_application    0
dtype: int64

In [89]:
df.isnull().sum()

ID                               0
year                             0
loan_limit                       0
Gender                           0
approv_in_adv                    0
loan_type                        0
loan_purpose                     0
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                             0
Neg_ammortization                0
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                           0
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                              0
submission_of_application        0
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
interest_rate_missing            0
upfront_charges_missing          0
property_value_missing           0
dtir1_missing                    0
dtype: int64

In [90]:
df["loan_to_income_ratio"] = df["loan_amount"] / df["income"]

In [91]:
df[["loan_amount", "income", "loan_to_income_ratio"]].head()

   loan_amount   income  loan_to_income_ratio
0       116500   1740.0             66.954023
1       206500   4980.0             41.465863
2       406500   9480.0             42.879747
3       456500  11880.0             38.425926
4       696500  10440.0             66.714559

In [92]:
df["loan_to_income_ratio"].describe()

count    1.486700e+05
mean              inf
std               NaN
min      5.992573e-01
25%      3.758681e+01
50%      5.283565e+01
75%      7.099156e+01
max               inf
Name: loan_to_income_ratio, dtype: float64

In [93]:
df["income"].eq(0).sum()

np.int64(1260)

In [94]:
df.loc[df["income"] == 0, ["ID", "loan_amount", "income", "Status"]].head(10)

        ID  loan_amount  income  Status
42   24932       466500     0.0       1
143  25033       686500     0.0       1
208  25098       366500     0.0       1
301  25191       636500     0.0       1
409  25299       516500     0.0       1
463  25353       356500     0.0       1
586  25476       216500     0.0       1
589  25479       456500     0.0       1
593  25483       136500     0.0       1
743  25633       316500     0.0       1

In [95]:
df["income"].eq(0).sum()

np.int64(1260)

In [96]:
df.loc[df["income"] == 0, "Status"].value_counts()

Status
1    1252
0       8
Name: count, dtype: int64

In [98]:
df.loc[df["income"] == 0, "loan_to_income_ratio"] = pd.NA

In [99]:
df["loan_to_income_ratio"].describe()

count    147410.000000
mean         56.952726
std          92.785932
min           0.599257
25%          37.500000
50%          52.555556
75%          70.502646
max       25275.000000
Name: loan_to_income_ratio, dtype: float64

In [100]:
df.loc[
    df["loan_to_income_ratio"] > 200,
    ["ID", "loan_amount", "income", "loan_to_income_ratio", "Status"]
].sort_values(
    "loan_to_income_ratio",
    ascending=False
).head(10)

            ID  loan_amount  income  loan_to_income_ratio  Status
30376    55266      1516500    60.0          25275.000000       1
123826  148716      1386500   120.0          11554.166667       1
99124   124014       566500    60.0           9441.666667       1
147719  172609       946500   120.0           7887.500000       1
22222    47112       336500    60.0           5608.333333       1
111517  136407       296500    60.0           4941.666667       1
25467    50357      1646500   360.0           4573.611111       1
43079    67969       486500   120.0           4054.166667       0
97078   121968       486500   120.0           4054.166667       0
140328  165218       906500   240.0           3777.083333       1

In [101]:
df["loan_to_income_group"] = pd.qcut(
    df["loan_to_income_ratio"],
    q=5,
    duplicates="drop"
)

df.groupby("loan_to_income_group", observed=True)["Status"].agg(
    ["count", "mean"]
)

                      count      mean
loan_to_income_group
(0.598, 34.115]       29560  0.231258
(34.115, 46.472]      29404  0.220752
(46.472, 58.984]      29494  0.222995
(58.984, 75.227]      29480  0.227748
(75.227, 25275.0]     29472  0.297537

In [102]:
df["loan_to_property_ratio"] = (
    df["loan_amount"] / df["property_value"]
)

In [103]:
df[[
    "loan_amount",
    "property_value",
    "loan_to_property_ratio"
]].head()

   loan_amount  property_value  loan_to_property_ratio
0       116500        118000.0                0.987288
1       206500             NaN                     NaN
2       406500        508000.0                0.800197
3       456500        658000.0                0.693769
4       696500        758000.0                0.918865

In [3]:
df["loan_to_property_ratio"] = (
    df["loan_amount"] / df["property_value"]
)

In [4]:
df[[
    "loan_amount",
    "property_value",
    "loan_to_property_ratio"
]].head()

   loan_amount  property_value  loan_to_property_ratio
0       116500        118000.0                0.987288
1       206500             NaN                     NaN
2       406500        508000.0                0.800197
3       456500        658000.0                0.693769
4       696500        758000.0                0.918865

In [5]:
df["loan_to_property_ratio"].describe()

count    133572.000000
mean          0.727465
std           0.399676
min           0.009675
25%           0.604749
50%           0.751359
75%           0.861842
max          78.312500
Name: loan_to_property_ratio, dtype: float64

In [6]:
df.loc[
    df["loan_to_property_ratio"] > 2,
    ["ID", "loan_amount", "property_value",
     "loan_to_property_ratio", "LTV", "Status"]
].sort_values(
    "loan_to_property_ratio",
    ascending=False
).head(10)

,ID,loan_amount,property_value,loan_to_property_ratio,LTV,Status
16951,41841,626500,8000.0,78.312500,7831.250000,0
55286,80176,536500,8000.0,67.062500,6706.250000,0
47807,72697,416500,8000.0,52.062500,5206.250000,0
65238,90128,376500,8000.0,47.062500,4706.250000,0
46287,71177,236500,8000.0,29.562500,2956.250000,1
123343,148233,186500,8000.0,23.312500,2331.250000,0
43348,68238,126500,48000.0,2.635417,263.541667,1
27473,52363,66500,28000.0,2.375000,237.500000,1
30837,55727,66500,28000.0,2.375000,237.500000,1
136154,161044,546500,248000.0,2.203629,220.362903,0

In [7]:
df.loc[
    df["property_value"] <= 50000,
    ["ID", "loan_amount", "property_value",
     "loan_to_property_ratio", "LTV", "Status"]
].sort_values(
    "property_value"
).head(20)

,ID,loan_amount,property_value,loan_to_property_ratio,LTV,Status
55286,80176,536500,8000.0,67.062500,6706.250000,0
47807,72697,416500,8000.0,52.062500,5206.250000,0
46287,71177,236500,8000.0,29.562500,2956.250000,1
65238,90128,376500,8000.0,47.062500,4706.250000,0
16951,41841,626500,8000.0,78.312500,7831.250000,0
123343,148233,186500,8000.0,23.312500,2331.250000,0
136556,161446,16500,18000.0,0.916667,91.666667,1
53248,78138,26500,28000.0,0.946429,94.642857,0
58211,83101,26500,28000.0,0.946429,94.642857,1
43224,68114,26500,28000.0,0.946429,94.642857,1
131734,156624,46500,28000.0,1.660714,166.071429,1
30837,55727,66500,28000.0,2.375000,237.500000,1
27473,52363,66500,28000.0,2.375000,237.500000,1
51248,76138,56500,28000.0,2.017857,201.785714,1
82307,107197,26500,28000.0,0.946429,94.642857,0
97052,121942,46500,28000.0,1.660714,166.071429,1
115653,140543,36500,38000.0,0.960526,96.052632,0
99237,124127,36500,38000.0,0.960526,96.052632,1
53831,78721,36500,38000.0,0.960526,96.052632,1
100533,125423,26500,38000.0,0.697368,69.736842,0

In [8]:
df.loc[
    df["loan_to_property_ratio"] > 1,
    ["ID", "loan_amount", "property_value",
     "loan_to_property_ratio", "LTV", "Status"]
].shape

(1799, 6)

In [9]:
df.loc[
    df["loan_to_property_ratio"] > 1,
    "Status"
].value_counts()

Status
1    1171
0     628
Name: count, dtype: int64

In [10]:
df["loan_to_property_ratio"].describe()

count    133572.000000
mean          0.727465
std           0.399676
min           0.009675
25%           0.604749
50%           0.751359
75%           0.861842
max          78.312500
Name: loan_to_property_ratio, dtype: float64

In [11]:
df["loan_to_property_group"] = pd.cut(
    df["loan_to_property_ratio"],
    bins=[0, 0.50, 0.75, 1.00, float("inf")],
    labels=[
        "Low",
        "Moderate",
        "High",
        "Very High"
    ],
    include_lowest=True
)

df.groupby(
    "loan_to_property_group",
    observed=True
)["Status"].agg(
    ["count", "mean"]
)

                        count      mean
loan_to_property_group
Low                     16851  0.150970
Moderate                48810  0.125876
High                    66112  0.176730
Very High                1799  0.650917

In [12]:
df["credit_score_group"] = pd.cut(
    df["Credit_Score"],
    bins=[0, 599, 699, 799, 900],
    labels=[
        "Low",
        "Fair",
        "Good",
        "Very Good"
    ],
    include_lowest=True
)

In [13]:
df.groupby(
    "credit_score_group",
    observed=True
)["Status"].agg(
    ["count", "mean"]
)

                    count      mean
credit_score_group
Low                 37190  0.246303
Fair                37200  0.244839
Good                36811  0.242862
Very Good           37469  0.251701

In [14]:
df["dtir_group"] = pd.cut(
    df["dtir1"],
    bins=[0, 30, 40, 50, float("inf")],
    labels=[
        "Low",
        "Moderate",
        "High",
        "Very High"
    ],
    include_lowest=True
)

In [15]:
df.groupby(
    "dtir_group",
    observed=True
)["Status"].agg(
    ["count", "mean"]
)

            count      mean
dtir_group
Low         27970  0.156024
Moderate    41861  0.122047
High        46079  0.155472
Very High    8639  0.427364

In [16]:
df["loan_amount_group"] = pd.cut(
    df["loan_amount"],
    bins=[0, 200000, 400000, 600000, float("inf")],
    labels=[
        "Small",
        "Medium",
        "Large",
        "Very Large"
    ],
    include_lowest=True
)

In [17]:
df.groupby(
    "loan_amount_group",
    observed=True
)["Status"].agg(
    ["count", "mean"]
)

                   count      mean
loan_amount_group
Small              38326  0.299144
Medium             64873  0.234520
Large              33433  0.206652
Very Large         12038  0.253447

In [18]:
df["income_group"] = pd.cut(
    df["income"],
    bins=[0, 3000, 5000, 7000, 10000, float("inf")],
    labels=[
        "Low",
        "Lower-Middle",
        "Middle",
        "Upper-Middle",
        "High"
    ],
    include_lowest=True
)

In [19]:
df.groupby(
    "income_group",
    observed=True
)["Status"].agg(
    ["count", "mean"]
)

              count      mean
income_group
Low           22308  0.397660
Lower-Middle  35328  0.265087
Middle        30204  0.221891
Upper-Middle  27936  0.201353
High          23744  0.203715

In [22]:
df["interest_rate_missing"] = df["rate_of_interest"].isna().astype(int)

df["upfront_charges_missing"] = df["Upfront_charges"].isna().astype(int)

df["property_value_missing"] = df["property_value"].isna().astype(int)

df["dtir1_missing"] = df["dtir1"].isna().astype(int)

In [23]:
df[
    [
        "interest_rate_missing",
        "upfront_charges_missing",
        "property_value_missing",
        "dtir1_missing"
    ]
].head()

,interest_rate_missing,upfront_charges_missing,property_value_missing,dtir1_missing
0,1,1,0,0
1,1,1,1,1
2,0,0,0,0
3,0,1,0,0
4,0,0,0,0

In [24]:
df["financial_missing_count"] = (
    df[
        [
            "interest_rate_missing",
            "upfront_charges_missing",
            "property_value_missing",
            "dtir1_missing"
        ]
    ].sum(axis=1)
)

In [25]:
df.groupby(
    "financial_missing_count"
)["Status"].agg(
    ["count", "mean"]
)

                          count      mean
financial_missing_count
0                        101430  0.000000
1                         10386  0.014731
2                         20744  0.982260
3                          1014  1.000000
4                         15096  1.000000

In [26]:
df.to_csv("Bank_Loan_Default_Cleaned.csv", index=False)

In [27]:
df.shape

(148670, 53)

In [28]:
df.columns.tolist()

['ID',
 'year',
 'loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'loan_amount',
 'rate_of_interest',
 'Interest_rate_spread',
 'Upfront_charges',
 'term',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'property_value',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'income',
 'credit_type',
 'Credit_Score',
 'co-applicant_credit_type',
 'age',
 'submission_of_application',
 'LTV',
 'Region',
 'Security_Type',
 'Status',
 'dtir1',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'loan_to_property_ratio',
 'loan_to_property_group',
 'credit_score_group',
 'dtir_group',
 'loan_amount_group',
 'income_group',
 'interest_rate_missing',
 'upfront_charges_missing',
 'property_value_missing',
 'dtir1_missing',
 'financial_missing_count']

In [29]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")]
df = df.copy()

In [30]:
df.shape

(148670, 45)

In [31]:
df.columns.tolist()

['ID',
 'year',
 'loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'loan_amount',
 'rate_of_interest',
 'Interest_rate_spread',
 'Upfront_charges',
 'term',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'property_value',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'income',
 'credit_type',
 'Credit_Score',
 'co-applicant_credit_type',
 'age',
 'submission_of_application',
 'LTV',
 'Region',
 'Security_Type',
 'Status',
 'dtir1',
 'loan_to_property_ratio',
 'loan_to_property_group',
 'credit_score_group',
 'dtir_group',
 'loan_amount_group',
 'income_group',
 'interest_rate_missing',
 'upfront_charges_missing',
 'property_value_missing',
 'dtir1_missing',
 'financial_missing_count']

In [32]:
df.to_csv("Bank_Loan_Default_Cleaned.csv", index=False)

In [33]:
df["term"] = df["term"].fillna(360)

In [34]:
df["term"].isna().sum()

np.int64(0)

In [35]:
df.to_csv("Bank_Loan_Default_Cleaned.csv", index=False)

In [36]:
df["Neg_ammortization"] = df["Neg_ammortization"].fillna("not_neg")

In [37]:
df["Neg_ammortization"].isna().sum()

np.int64(0)

In [38]:
df.isna().sum()[df.isna().sum() > 0]

loan_limit                    3344
approv_in_adv                  908
loan_purpose                   134
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
property_value               15098
income                        9150
age                            200
submission_of_application      200
LTV                          15098
dtir1                        24121
loan_to_property_ratio       15098
loan_to_property_group       15098
dtir_group                   24121
income_group                  9150
dtype: int64

In [39]:
df["loan_limit"] = df["loan_limit"].fillna("cf")
df["approv_in_adv"] = df["approv_in_adv"].fillna("nopre")
df["loan_purpose"] = df["loan_purpose"].fillna("p3")
df["income"] = df["income"].fillna(df["income"].median())
df["age"] = df["age"].fillna("45-54")
df["submission_of_application"] = df["submission_of_application"].fillna("to_inst")

In [40]:
df.to_csv("Bank_Loan_Default_Cleaned.csv", index=False)

In [41]:
df = df.rename(
    columns={
        "co-applicant_credit_type": "co_applicant_credit_type"
    }
)

In [42]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")]
df = df.copy()

In [43]:
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")]
df = df.copy()

In [44]:
df.shape

(148670, 45)

In [45]:
df.columns.tolist()

['ID',
 'year',
 'loan_limit',
 'Gender',
 'approv_in_adv',
 'loan_type',
 'loan_purpose',
 'Credit_Worthiness',
 'open_credit',
 'business_or_commercial',
 'loan_amount',
 'rate_of_interest',
 'Interest_rate_spread',
 'Upfront_charges',
 'term',
 'Neg_ammortization',
 'interest_only',
 'lump_sum_payment',
 'property_value',
 'construction_type',
 'occupancy_type',
 'Secured_by',
 'total_units',
 'income',
 'credit_type',
 'Credit_Score',
 'co_applicant_credit_type',
 'age',
 'submission_of_application',
 'LTV',
 'Region',
 'Security_Type',
 'Status',
 'dtir1',
 'loan_to_property_ratio',
 'loan_to_property_group',
 'credit_score_group',
 'dtir_group',
 'loan_amount_group',
 'income_group',
 'interest_rate_missing',
 'upfront_charges_missing',
 'property_value_missing',
 'dtir1_missing',
 'financial_missing_count']

In [46]:
df.to_csv(
    "Bank_Loan_Default_Cleaned.csv",
    index=False
)

In [47]:
df["term"] = pd.to_numeric(df["term"], errors="coerce").fillna(360).astype(int)

In [48]:
df["term"].dtype

dtype('int64')

In [49]:
df["term"].unique()

array([360, 300, 180, 312, 144, 240, 348, 324, 120,  96, 192, 156, 228,
       336, 288, 108, 276, 132, 216, 168, 204, 264, 252, 165, 280, 322])

In [50]:
df.to_csv(
    "Bank_Loan_Default_Cleaned.csv",
    index=False
)